Feature/add config params
boschresearch/ros_license_toolkit pull request #71
Opened 2024-12-05 08:23 UTC by ant-u

First: merge feature/adapt_tests_for_warning

Here, the params -continue_on_error and -errors_as_warnings are introduced.

Also, some more testcases are added.

2024-12-09 20:36 UTC, ct2034 requested changes

2024-12-09 20:36 UTC, ct2034 commented on src/ros_license_toolkit/checks.py
> +
```suggestion
```

2024-12-09 20:36 UTC, ct2034 commented on src/ros_license_toolkit/license_checks/license_in_code_check.py
> +        # self.package_xml_vers = package_xml_version
please remove

2024-12-09 20:36 UTC, ct2034 commented on src/ros_license_toolkit/license_checks/schema_check.py
> +# Copyright (c) 2024 - for information on the respective copyright owner
Please implement all my comments from #70

2024-12-16 09:32 UTC, ct2034 requested changes

2024-12-16 09:32 UTC, ct2034 commented on src/ros_license_toolkit/license_checks/schema_check.py
> +from typing import Tuple
```suggestion
from typing import Optional, Tuple
```

2025-01-13 14:47 UTC, ant-u commented
Error in documentation_test was that the ros_license_toolkit -h command inserts line breaks when operated with subprocess.Popen(). Therefore I added the same line break in the documentation. Another (future) possibility would be to ignore these exact kinds of line breaks. For now it would just add unnecessary overhead.

2025-01-13 16:08 UTC, ct2034 approved these changes

2025-01-13 16:13 UTC, merged